# Generated by Django 4.0.6 on 2022-07-27 17:45

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spirit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=15, null=True)),
                ('name', models.CharField(max_length=100)),
                ('realm', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WingedLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm', models.CharField(choices=[('Isle of Dawn', 'Isle'), ('Daylight Prairie', 'Daylight'), ('Hidden Forest', 'Forest'), ('Valley of Triump', 'Valley'), ('Golden Wasteland', 'Wasteland'), ('Vault of Knowledge', 'Vault'), ('Secret Area', 'Secret')], default='Isle of Dawn', max_length=20)),
                ('location', ckeditor.fields.RichTextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['realm'],
            },
        ),
        migrations.CreateModel(
            name='UserSpirit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('Candlemaker', 'Candlemaker'), ('Stargazer', 'Stargazer'), ('Voyager', 'Voyager'), ('Charmer', 'Charmer'), ('Bellmaker', 'Bellmaker')], default='Candlemaker', max_length=15, null=True)),
                ('name', models.CharField(max_length=100)),
                ('realm', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(null=True, upload_to='images/profile')),
                ('pic_url', models.CharField(max_length=250, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
