# Generated by Django 4.0.6 on 2022-07-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
