# Generated by Django 4.0.6 on 2022-07-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profile_pic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic_url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
