# Generated by Django 4.0.6 on 2022-07-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_spirit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spirit',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='spirit',
            name='name',
            field=models.CharField(choices=[('Candlemaker', 'Pointing-Candlemaker'), ('Stargazer', 'Ushering-Stargazer'), ('Voyager', 'Rejecting-Voyager'), ('Charmer', 'Butterfly-Charmer'), ('Bellmaker', 'Waving-Bellmaker')], default='Candlemaker', max_length=50),
        ),
    ]
