# Generated by Django 4.0.6 on 2022-07-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_spirit_options_alter_spirit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspirit',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
