# Generated by Django 4.0.6 on 2022-07-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_spirit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spirit',
            name='name',
            field=models.CharField(choices=[('Candlemaker', 'Candlemaker'), ('Stargazer', 'Stargazer'), ('Voyager', 'Voyager'), ('Charmer', 'Charmer'), ('Bellmaker', 'Bellmaker')], default='Candlemaker', max_length=29),
        ),
        migrations.AlterField(
            model_name='userspirit',
            name='name',
            field=models.CharField(choices=[('Candlemaker', 'Candlemaker'), ('Stargazer', 'Stargazer'), ('Voyager', 'Voyager'), ('Charmer', 'Charmer'), ('Bellmaker', 'Bellmaker')], default='Candlemaker', max_length=29),
        ),
    ]
