# Generated by Django 4.0.6 on 2022-07-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_spirit_name_alter_userspirit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='spirit',
            name='tag',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userspirit',
            name='tag',
            field=models.CharField(choices=[('Candlemaker', 'Candlemaker'), ('Stargazer', 'Stargazer'), ('Voyager', 'Voyager'), ('Charmer', 'Charmer'), ('Bellmaker', 'Bellmaker')], default='Candlemaker', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='spirit',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userspirit',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userspirit',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
