# Generated by Django 4.0.6 on 2022-07-27 15:36

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0015_spirit_tag_userspirit_tag_alter_spirit_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WingedLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm', models.CharField(choices=[('Isle of Dawn', 'Isle'), ('Daylight Prairie', 'Daylight'), ('Hidden Forest', 'Forest'), ('Valley of Triump', 'Valley'), ('Golden Wasteland', 'Wasteland'), ('Vault of Knowledge', 'Vault'), ('Secret Area', 'Secret')], default='Isle of Dawn', max_length=20)),
                ('location', ckeditor.fields.RichTextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['realm'],
            },
        ),
    ]
